"""empty message

Revision ID: 0feb23a72586
Revises: 165d51223a11
Create Date: 2026-01-19 15:19:05.487069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0feb23a72586'
down_revision = '165d51223a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['like_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('like_user_id')

    # ### end Alembic commands ###
