"""empty message

Revision ID: 165d51223a11
Revises: d740131ab5dc
Create Date: 2026-01-19 15:17:14.654316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165d51223a11'
down_revision = 'd740131ab5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('like_like_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('like_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('like_like_user_id_fkey', 'user', ['like_user_id'], ['id'])

    # ### end Alembic commands ###
