"""empty message

Revision ID: 2c20f23b0ba3
Revises: c88dc051d7bd
Create Date: 2026-01-19 10:55:00.684494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c20f23b0ba3'
down_revision = 'c88dc051d7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('id_post')
        batch_op.drop_column('id_user')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_column('id_post')
        batch_op.drop_column('id_user')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_post', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_post', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
