"""empty message

Revision ID: 41ec374bfd35
Revises: cc9d527d3a20
Create Date: 2026-01-18 23:22:10.963873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ec374bfd35'
down_revision = 'cc9d527d3a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comment_post_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('comment_post_id_fkey', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('comment_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
