"""empty message

Revision ID: 518567ac349e
Revises: 9f11c892a194
Create Date: 2026-01-19 14:20:07.623991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518567ac349e'
down_revision = '9f11c892a194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_column('follow_by')
        batch_op.drop_column('follow_of')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_of', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('follow_by', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
