"""empty message

Revision ID: 538b4f46ab0b
Revises: abb059784d50
Create Date: 2026-01-19 14:49:44.667482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538b4f46ab0b'
down_revision = 'abb059784d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_post_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'post', ['like_post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('like_post_id')

    # ### end Alembic commands ###
