"""empty message

Revision ID: 61b5d5980c34
Revises: 0feb23a72586
Create Date: 2026-01-19 15:24:15.315245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b5d5980c34'
down_revision = '0feb23a72586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['follower_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('follower_user_id')

    # ### end Alembic commands ###
