"""empty message

Revision ID: 8b99682aac6e
Revises: 518567ac349e
Create Date: 2026-01-19 14:21:44.214065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b99682aac6e'
down_revision = '518567ac349e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authot_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['authot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('authot_id')

    # ### end Alembic commands ###
