"""empty message

Revision ID: 9f11c892a194
Revises: 2c20f23b0ba3
Create Date: 2026-01-19 14:19:17.187955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f11c892a194'
down_revision = '2c20f23b0ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comment_post_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint('follower_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('like_user_list_key', type_='unique')
        batch_op.drop_constraint('like_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('like_post_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('post_id')
        batch_op.drop_column('user_list')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_list', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['user_list'])
        batch_op.drop_constraint('post_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('post_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_list')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_list', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('like_post_id_fkey', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('like_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_unique_constraint('like_user_list_key', ['user_list'])

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('follower_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('comment_post_id_fkey', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('comment_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
