"""empty message

Revision ID: abb059784d50
Revises: 8b99682aac6e
Create Date: 2026-01-19 14:37:27.763162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb059784d50'
down_revision = '8b99682aac6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_authot_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('comment_post_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'post', ['comment_post_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['comment_authot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comment_post_id')
        batch_op.drop_column('comment_authot_id')

    # ### end Alembic commands ###
