"""empty message

Revision ID: d00875e27738
Revises: ed03b47fd1d6
Create Date: 2026-01-18 22:19:38.899659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00875e27738'
down_revision = 'ed03b47fd1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follow_of', sa.Integer(), nullable=False),
    sa.Column('follow_by', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('follow_of', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('follow_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='followers_pkey')
    )
    op.drop_table('follower')
    # ### end Alembic commands ###
