"""empty message

Revision ID: d740131ab5dc
Revises: 538b4f46ab0b
Create Date: 2026-01-19 14:53:16.966910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd740131ab5dc'
down_revision = '538b4f46ab0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['like_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('like_user_id')

    # ### end Alembic commands ###
