"""empty message

Revision ID: df22a0234b91
Revises: 61b5d5980c34
Create Date: 2026-01-19 15:33:21.507900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df22a0234b91'
down_revision = '61b5d5980c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_author_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('comment_comment_authot_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['comment_author_id'], ['id'])
        batch_op.drop_column('comment_authot_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('post_authot_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])
        batch_op.drop_column('authot_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authot_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_authot_id_fkey', 'user', ['authot_id'], ['id'])
        batch_op.drop_column('author_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_authot_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_comment_authot_id_fkey', 'user', ['comment_authot_id'], ['id'])
        batch_op.drop_column('comment_author_id')

    # ### end Alembic commands ###
