"""empty message

Revision ID: eff3fcc1d114
Revises: df22a0234b91
Create Date: 2026-01-19 15:40:39.432932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff3fcc1d114'
down_revision = 'df22a0234b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_text_key', type_='unique')

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_by_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('follower_of_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('follower_follower_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['follower_by_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['follower_of_user_id'], ['id'])
        batch_op.drop_column('follower_user_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_post_img_key', type_='unique')
        batch_op.drop_constraint('post_user_list_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_unique_constraint('post_user_list_key', ['user_list'])
        batch_op.create_unique_constraint('post_post_img_key', ['post_img'])

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follower_follower_user_id_fkey', 'user', ['follower_user_id'], ['id'])
        batch_op.drop_column('follower_of_user_id')
        batch_op.drop_column('follower_by_user_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_unique_constraint('comment_text_key', ['text'])

    # ### end Alembic commands ###
